---
driver:
  name: gce

platforms:
  - name: molecule-apache-vm
    zone: us-central1-a
    machine_type: e2-medium
    image_project: ubuntu-os-cloud
    image_family: ubuntu-2204-lts
    project: YOUR_GCP_PROJECT_ID
    ssh_user: ubuntu

provisioner:
  name: ansible
  playbooks:
    converge: converge.yaml

verifier:
  name: ansible

